// Builds the original doodle art used across the night market.
//
//   public/doodles/banner-<n>.svg   8 wide stall banners (1024 x 512)
//   public/doodles/<stamp>.svg      the individual characters (200 x 200)
//   public/doodles/atlas.webp       2048 x 2048 texture: the 8 banners in a
//                                   2 x 4 grid, sampled by the 3D stalls
//   lib/doodleAtlas.generated.ts
//
// Run: npm run assets:doodles
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Resvg } from "@resvg/resvg-js";
import sharp from "sharp";
import { BANNER_COUNT, BANNER_H, BANNER_W, STAMP_NAMES, SYRUP, banner, stamps } from "./doodles.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const OUT = join(ROOT, "public", "doodles");
const COLS = 2;
const SIZE = 2048; // the atlas never exceeds this

if (BANNER_COUNT > COLS * (SIZE / BANNER_H)) throw new Error("atlas is full");
mkdirSync(OUT, { recursive: true });

const minify = (s) => s.replace(/\n\s*/g, "").replace(/\s{2,}/g, " ");

const banners = [];
for (let i = 0; i < BANNER_COUNT; i++) {
  const body = banner(i);
  banners.push(body);
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${BANNER_W} ${BANNER_H}" width="${BANNER_W}" height="${BANNER_H}">${body}</svg>`;
  writeFileSync(join(OUT, `banner-${i}.svg`), minify(svg));
}

const accents = [SYRUP.pink, SYRUP.green, SYRUP.yellow, SYRUP.purple, SYRUP.teal];
STAMP_NAMES.forEach((name, i) => {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="-12 -12 224 224" width="224" height="224">${stamps[name](accents[i % 5], accents[(i + 2) % 5])}</svg>`;
  writeFileSync(join(OUT, `${name}.svg`), minify(svg));
});

const cells = banners
  .map((body, i) => {
    const x = (i % COLS) * BANNER_W;
    const y = Math.floor(i / COLS) * BANNER_H;
    return `<svg x="${x}" y="${y}" width="${BANNER_W}" height="${BANNER_H}" viewBox="0 0 ${BANNER_W} ${BANNER_H}" overflow="hidden">${body}</svg>`;
  })
  .join("");
const atlas = minify(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${SIZE} ${SIZE}" width="${SIZE}" height="${SIZE}">${cells}</svg>`);
const png = new Resvg(atlas, { fitTo: { mode: "width", value: SIZE } }).render().asPng();
await sharp(png).webp({ quality: 82, effort: 6 }).toFile(join(OUT, "atlas.webp"));

const ts = `// Generated by scripts/doodles/build-doodles.mjs. Do not edit by hand.
export const BANNER_COUNT = ${BANNER_COUNT};
/** atlas.webp: ${SIZE}px, banners of ${BANNER_W}x${BANNER_H} in ${COLS} columns */
export const ATLAS = { size: ${SIZE}, cols: ${COLS}, rows: ${SIZE / BANNER_H} } as const;
export const STAMPS = ${JSON.stringify(STAMP_NAMES)} as const;
export type StampName = (typeof STAMPS)[number];
`;
writeFileSync(join(ROOT, "lib", "doodleAtlas.generated.ts"), ts);
console.log(`doodles: ${BANNER_COUNT} banners, ${STAMP_NAMES.length} stamps, atlas ${SIZE}px`);
