// Builds the doodle texture atlas used by both the WebGL doodle field and the
// in-panel DOM doodles.
//
//   public/doodles/atlas.svg    4x4 vector atlas (CSS sprites inside panels)
//   public/doodles/atlas.webp   2048x2048 raster atlas (Three.js texture)
//   public/doodles/<name>.svg   individual doodles
//   lib/doodleAtlas.generated.ts
//
// Run: npm run assets:doodles
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Resvg } from "@resvg/resvg-js";
import sharp from "sharp";
import { defs, doodles } from "./doodles.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const OUT = join(ROOT, "public", "doodles");
const CELL = 512;
const COLS = 4;
const SIZE = CELL * COLS; // 2048 — the atlas never exceeds this

if (doodles.length > COLS * COLS) throw new Error("atlas is full");
mkdirSync(OUT, { recursive: true });

const minify = (s) => s.replace(/\n\s*/g, "").replace(/\s{2,}/g, " ");

for (const d of doodles) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${CELL} ${CELL}"><defs>${defs}</defs>${d.svg}</svg>`;
  writeFileSync(join(OUT, `${d.name}.svg`), minify(svg));
}

const cells = doodles
  .map((d, i) => {
    const x = (i % COLS) * CELL;
    const y = Math.floor(i / COLS) * CELL;
    // clip each cell so nothing bleeds into its neighbour when sampled
    return `<svg x="${x}" y="${y}" width="${CELL}" height="${CELL}" viewBox="0 0 ${CELL} ${CELL}" overflow="hidden">${d.svg}</svg>`;
  })
  .join("");
const atlas = minify(
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${SIZE} ${SIZE}" width="${SIZE}" height="${SIZE}"><defs>${defs}</defs>${cells}</svg>`,
);
writeFileSync(join(OUT, "atlas.svg"), atlas);

const png = new Resvg(atlas, { fitTo: { mode: "width", value: SIZE } }).render().asPng();
await sharp(png).webp({ quality: 88, alphaQuality: 90, effort: 6 }).toFile(join(OUT, "atlas.webp"));

const ts = `// Generated by scripts/doodles/build-doodles.mjs. Do not edit by hand.
export const ATLAS_COLS = ${COLS};
export const ATLAS_SIZE = ${SIZE};
export const DOODLES = ${JSON.stringify(doodles.map((d) => d.name))} as const;
export type DoodleName = (typeof DOODLES)[number];
`;
writeFileSync(join(ROOT, "lib", "doodleAtlas.generated.ts"), ts);
console.log(`atlas: ${doodles.length} doodles, ${SIZE}px`);
