// Generated by scripts/audio/build-audio.mjs. Do not edit by hand.
export const SFX_SPRITE = {"beep":[30,180],"crush":[440,580],"rustle":[1250,430],"slurp":[1910,630],"fizz":[2770,930],"bite":[3930,480],"freeze":[4640,1030],"pricegun":[5900,330],"bagpop":[6460,780],"spill":[7470,1030],"jelly":[8730,830],"coins":[9790,1030],"printer":[11050,1030],"tear":[12310,430],"stamp":[12970,380],"drawer":[13580,1230],"crumple":[15040,730],"bin":[16000,830],"flip":[17060,480],"vending":[17770,1330],"laugh1":[19330,1640],"laugh2":[21200,1645],"laugh3":[23075,1950],"chain":[25255,930],"splash":[26415,580],"flicker":[27225,930],"neon":[28385,250],"box":[28865,730],"lid":[29825,430],"switch":[30485,280],"chime":[30995,1430],"slap":[32655,230],"nope":[33115,380]} as const;
export type SfxName = keyof typeof SFX_SPRITE;
/** Loop region inside ambience.mp3: [start ms, duration ms, loop]. */
export const AMBIENCE_LOOP: [number, number, boolean] = [10435, 20870, true];
