// Generated by scripts/audio/build-audio.mjs. Do not edit by hand.
export const SFX_SPRITE = {
  "laugh1": [
    30,
    1050
  ],
  "laugh2": [
    1260,
    1240
  ],
  "laugh3": [
    2680,
    1500
  ],
  "flap": [
    4360,
    930
  ],
  "squish": [
    5470,
    480
  ],
  "slurp": [
    6130,
    980
  ],
  "spin": [
    7290,
    930
  ],
  "clink": [
    8400,
    830
  ],
  "puff": [
    9410,
    1130
  ],
  "drip": [
    10720,
    930
  ],
  "stretch": [
    11830,
    1080
  ],
  "band": [
    13090,
    730
  ],
  "sparkle": [
    14000,
    1230
  ],
  "bubbles": [
    15410,
    1130
  ],
  "thud": [
    16720,
    480
  ],
  "pen": [
    17380,
    1830
  ],
  "rip": [
    19390,
    630
  ],
  "stamp": [
    20200,
    330
  ],
  "crumple": [
    20710,
    780
  ],
  "toss": [
    21670,
    930
  ],
  "tok": [
    22780,
    530
  ],
  "mail": [
    23490,
    930
  ],
  "unwrap": [
    24600,
    630
  ],
  "flame": [
    25410,
    730
  ],
  "snuff": [
    26320,
    530
  ],
  "click": [
    27030,
    110
  ]
} as const;
export type SfxName = keyof typeof SFX_SPRITE;
/** Loop region inside ambient.mp3: [start ms, duration ms, loop]. */
export const AMBIENT_LOOP: [number, number, boolean] = [8000, 16000, true];
