// Generated by scripts/audio/build-audio.mjs. Do not edit by hand.
export const SFX_SPRITE = {
  "flip": [
    30,
    530
  ],
  "pow": [
    790,
    680
  ],
  "ding": [
    1700,
    1330
  ],
  "crumple": [
    3260,
    780
  ],
  "scribble": [
    4270,
    630
  ],
  "type": [
    5130,
    100
  ],
  "klik": [
    5460,
    170
  ],
  "pop": [
    5860,
    150
  ],
  "zap": [
    6240,
    350
  ]
} as const;
export type SfxName = keyof typeof SFX_SPRITE;
/** Loop region inside chiptune.mp3: [start ms, duration ms, loop]. */
export const MUSIC_LOOP: [number, number, boolean] = [7500, 15000, true];
