// Generated by scripts/doodles/build-doodles.mjs. Do not edit by hand.
export const BANNER_COUNT = 8;
/** atlas.webp: 2048px, banners of 1024x512 in 2 columns */
export const ATLAS = { size: 2048, cols: 2, rows: 4 } as const;
export const STAMPS = ["skull","ghost","bone","puddle","robot","glass","puff","star","eyeball","hand"] as const;
export type StampName = (typeof STAMPS)[number];
