// Generated by scripts/doodles/build-doodles.mjs. Do not edit by hand.
export const ATLAS_COLS = 4;
export const ATLAS_SIZE = 2048;
export const DOODLES = ["skull-flame","ghost-grin","ghost-drip","bomb","mushroom","arrow","crown","bubble-yes","bubble-no","eyeball","bone","mail-monster","at-blob","lightning","paper-ball","splat-star"] as const;
export type DoodleName = (typeof DOODLES)[number];
