// Extracts the single-stroke handwriting used on the warung nota.
//
// Source: assets/fonts/EMSTech.svg, "EMS Tech" by Sheldon B. Michaels, an
// engraving (single-line) font derived from Architects Daughter, SIL Open
// Font License 1.1 (see assets/fonts/OFL.txt).
//
// Every glyph becomes a list of polylines (curves are flattened), so the
// browser can draw the address stroke by stroke and the zombie hand can
// follow the pen tip exactly.
//
//   lib/handFont.generated.ts
//
// Run: npm run assets:hand
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const src = readFileSync(join(ROOT, "assets", "fonts", "EMSTech.svg"), "utf8");
const ASCENT = 800;
const defAdv = Number(src.match(/<font [^>]*horiz-adv-x="([\d.]+)"/)[1]);

const decode = (u) =>
  u
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCharCode(parseInt(h, 16)))
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, "&");

/** SVG path (M, L, C only) -> polylines in y-down em units. */
function polylines(d) {
  const toks = d.match(/[MLC]|-?\d*\.?\d+(?:e-?\d+)?/gi) ?? [];
  const lines = [];
  let cur = null;
  let cmd = "M";
  let x = 0, y = 0;
  const P = (px, py) => [Math.round(px), Math.round(ASCENT - py)];
  for (let i = 0; i < toks.length; ) {
    if (/[MLC]/i.test(toks[i])) cmd = toks[i++].toUpperCase();
    const n = (k) => Number(toks[i + k]);
    if (cmd === "M") {
      x = n(0); y = n(1); i += 2;
      cur = [P(x, y)];
      lines.push(cur);
      cmd = "L";
    } else if (cmd === "L") {
      x = n(0); y = n(1); i += 2;
      cur.push(P(x, y));
    } else if (cmd === "C") {
      const [x1, y1, x2, y2, x3, y3] = [n(0), n(1), n(2), n(3), n(4), n(5)];
      i += 6;
      for (let s = 1; s <= 8; s++) {
        const t = s / 8, u = 1 - t;
        cur.push(P(u * u * u * x + 3 * u * u * t * x1 + 3 * u * t * t * x2 + t * t * t * x3,
          u * u * u * y + 3 * u * u * t * y1 + 3 * u * t * t * y2 + t * t * t * y3));
      }
      x = x3; y = y3;
    }
  }
  // drop duplicate consecutive points
  return lines.map((l) => l.filter((p, k) => k === 0 || p[0] !== l[k - 1][0] || p[1] !== l[k - 1][1])).filter((l) => l.length > 1);
}

const glyphs = {};
for (const m of src.matchAll(/<glyph unicode="([^"]+)"[^>]*?horiz-adv-x="([\d.]+)"(?:\s+d="([^"]*)")?/g)) {
  const ch = decode(m[1]);
  if (ch.length !== 1) continue;
  const code = ch.charCodeAt(0);
  if (code < 32 || code > 126) continue;
  const strokes = m[3] ? polylines(m[3]) : [];
  glyphs[ch] = [Math.round(Number(m[2])), strokes.map((l) => l.flat().join(" ")).join("|")];
}

const ts = `// Generated by scripts/hand/build-hand.mjs from EMS Tech (SIL OFL 1.1). Do not edit by hand.
/** Single-stroke glyphs: [advance, "x y x y ...|x y ..."] in 1000-unit em, y down, baseline at ${ASCENT}. */
export const HAND_FONT = {
  ascent: ${ASCENT},
  defaultAdvance: ${defAdv},
  glyphs: ${JSON.stringify(glyphs)} as Record<string, [number, string]>,
};
`;
writeFileSync(join(ROOT, "lib", "handFont.generated.ts"), ts);
console.log("hand font:", Object.keys(glyphs).length, "glyphs,", ts.length, "bytes");
