// Generated by scripts/mascot/trace_mascot.py. Do not edit by hand.
export const BIRD_GEOMETRY = {
  "width": 798,
  "height": 756,
  "barAngle": 4.7,
  "bar": [
    [
      249.0,
      108.5
    ],
    [
      503.0,
      129.4
    ],
    [
      503.0,
      161.4
    ],
    [
      249.0,
      140.5
    ]
  ],
  "barPivot": [
    376.0,
    108.5
  ],
  "eye": {
    "cx": 374.5,
    "cy": 151.0,
    "rx": 110.5,
    "ry": 81.5,
    "stroke": 8.0
  },
  "split": [
    24.2,
    -85.5,
    1.2,
    76.2
  ]
} as const;
